'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MngService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ErrorLog", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ErrorLog
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreateTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMsgField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessInstanceField As MngService.ProcessInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActInstId() As Integer
            Get
                Return Me.ActInstIdField
            End Get
            Set
                If (Me.ActInstIdField.Equals(value) <> true) Then
                    Me.ActInstIdField = value
                    Me.RaisePropertyChanged("ActInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreateTime() As Date
            Get
                Return Me.CreateTimeField
            End Get
            Set
                If (Me.CreateTimeField.Equals(value) <> true) Then
                    Me.CreateTimeField = value
                    Me.RaisePropertyChanged("CreateTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMsg() As String
            Get
                Return Me.ErrorMsgField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMsgField, value) <> true) Then
                    Me.ErrorMsgField = value
                    Me.RaisePropertyChanged("ErrorMsg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventInstId() As Integer
            Get
                Return Me.EventInstIdField
            End Get
            Set
                If (Me.EventInstIdField.Equals(value) <> true) Then
                    Me.EventInstIdField = value
                    Me.RaisePropertyChanged("EventInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LogId() As Integer
            Get
                Return Me.LogIdField
            End Get
            Set
                If (Me.LogIdField.Equals(value) <> true) Then
                    Me.LogIdField = value
                    Me.RaisePropertyChanged("LogId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcInstId() As Integer
            Get
                Return Me.ProcInstIdField
            End Get
            Set
                If (Me.ProcInstIdField.Equals(value) <> true) Then
                    Me.ProcInstIdField = value
                    Me.RaisePropertyChanged("ProcInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessInstance() As MngService.ProcessInstance
            Get
                Return Me.ProcessInstanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessInstanceField, value) <> true) Then
                    Me.ProcessInstanceField = value
                    Me.RaisePropertyChanged("ProcessInstance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Source() As String
            Get
                Return Me.SourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceField, value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProcessInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProcessInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataFieldsField() As MngService.DataFieldDefinitionWithValue
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginatorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriorityField As MngService.ProcessInstance.ProcessPriority
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartDateField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataFields() As MngService.DataFieldDefinitionWithValue()
            Get
                Return Me.DataFieldsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataFieldsField, value) <> true) Then
                    Me.DataFieldsField = value
                    Me.RaisePropertyChanged("DataFields")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayName() As String
            Get
                Return Me.DisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayNameField, value) <> true) Then
                    Me.DisplayNameField = value
                    Me.RaisePropertyChanged("DisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Originator() As String
            Get
                Return Me.OriginatorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginatorField, value) <> true) Then
                    Me.OriginatorField = value
                    Me.RaisePropertyChanged("Originator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Priority() As MngService.ProcessInstance.ProcessPriority
            Get
                Return Me.PriorityField
            End Get
            Set
                If (Me.PriorityField.Equals(value) <> true) Then
                    Me.PriorityField = value
                    Me.RaisePropertyChanged("Priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessName() As String
            Get
                Return Me.ProcessNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessNameField, value) <> true) Then
                    Me.ProcessNameField = value
                    Me.RaisePropertyChanged("ProcessName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartDate() As Date
            Get
                Return Me.StartDateField
            End Get
            Set
                If (Me.StartDateField.Equals(value) <> true) Then
                    Me.StartDateField = value
                    Me.RaisePropertyChanged("StartDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="ProcessInstance.ProcessPriority", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model")>  _
        Public Enum ProcessPriority As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Normal = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Important = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Urgent = 2
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DataFieldDefinitionWithValue", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.ErrorLog())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.ErrorLog)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.ProcessInstance)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.DataFieldDefinitionWithValue())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.DataFieldDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.BaseDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.ProcessInstance.ProcessPriority))>  _
    Partial Public Class DataFieldDefinitionWithValue
        Inherits MngService.DataFieldDefinition
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueField As Object
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As Object
            Get
                Return Me.ValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueField, value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BaseDefinition", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.DataFieldDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.DataFieldDefinitionWithValue))>  _
    Partial Public Class BaseDefinition
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DataFieldDefinition", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MngService.DataFieldDefinitionWithValue))>  _
    Partial Public Class DataFieldDefinition
        Inherits MngService.BaseDefinition
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MngService.IManagementService")>  _
    Public Interface IManagementService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagementService/GetAllErrorlogs", ReplyAction:="http://tempuri.org/IManagementService/GetAllErrorlogsResponse")>  _
        Function GetAllErrorlogs() As MngService.ErrorLog()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IManagementService/RetryError", ReplyAction:="http://tempuri.org/IManagementService/RetryErrorResponse")>  _
        Sub RetryError(ByVal errorId As Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IManagementServiceChannel
        Inherits MngService.IManagementService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ManagementServiceClient
        Inherits System.ServiceModel.ClientBase(Of MngService.IManagementService)
        Implements MngService.IManagementService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllErrorlogs() As MngService.ErrorLog() Implements MngService.IManagementService.GetAllErrorlogs
            Return MyBase.Channel.GetAllErrorlogs
        End Function
        
        Public Sub RetryError(ByVal errorId As Integer) Implements MngService.IManagementService.RetryError
            MyBase.Channel.RetryError(errorId)
        End Sub
    End Class
End Namespace
