'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WorkflowServer
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProcessInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProcessInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataFieldsField() As WorkflowServer.DataFieldDefinitionWithValue
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginatorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriorityField As WorkflowServer.ProcessInstance.ProcessPriority
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartDateField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataFields() As WorkflowServer.DataFieldDefinitionWithValue()
            Get
                Return Me.DataFieldsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataFieldsField, value) <> true) Then
                    Me.DataFieldsField = value
                    Me.RaisePropertyChanged("DataFields")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayName() As String
            Get
                Return Me.DisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayNameField, value) <> true) Then
                    Me.DisplayNameField = value
                    Me.RaisePropertyChanged("DisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Originator() As String
            Get
                Return Me.OriginatorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginatorField, value) <> true) Then
                    Me.OriginatorField = value
                    Me.RaisePropertyChanged("Originator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Priority() As WorkflowServer.ProcessInstance.ProcessPriority
            Get
                Return Me.PriorityField
            End Get
            Set
                If (Me.PriorityField.Equals(value) <> true) Then
                    Me.PriorityField = value
                    Me.RaisePropertyChanged("Priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessName() As String
            Get
                Return Me.ProcessNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessNameField, value) <> true) Then
                    Me.ProcessNameField = value
                    Me.RaisePropertyChanged("ProcessName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartDate() As Date
            Get
                Return Me.StartDateField
            End Get
            Set
                If (Me.StartDateField.Equals(value) <> true) Then
                    Me.StartDateField = value
                    Me.RaisePropertyChanged("StartDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="ProcessInstance.ProcessPriority", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model")>  _
        Public Enum ProcessPriority As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Normal = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Important = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Urgent = 2
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DataFieldDefinitionWithValue", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.ProcessInstance)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinitionWithValue())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.BaseDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.ProcessInstance.ProcessPriority)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.WorklistItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.WorklistItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.ActivityDestinationInstance)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.ActivityStatus)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.ActivityInstance)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DestinationSlot)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.WorklistItemStatu)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Object))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Integer())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String()))>  _
    Partial Public Class DataFieldDefinitionWithValue
        Inherits WorkflowServer.DataFieldDefinition
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueField As Object
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As Object
            Get
                Return Me.ValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueField, value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BaseDefinition", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinition)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinitionWithValue))>  _
    Partial Public Class BaseDefinition
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DataFieldDefinition", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinitionWithValue))>  _
    Partial Public Class DataFieldDefinition
        Inherits WorkflowServer.BaseDefinition
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WorklistItem", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WorklistItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivityDestinationInstanceField As WorkflowServer.ActivityDestinationInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivityInstanceField As WorkflowServer.ActivityInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivityNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreateDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationSlotField As WorkflowServer.DestinationSlot
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemDataField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginatorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriorityField As WorkflowServer.ProcessInstance.ProcessPriority
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcInstIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcSchemeDisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessDisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessInstanceField As WorkflowServer.ProcessInstance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As WorkflowServer.WorklistItemStatu
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActInstId() As Integer
            Get
                Return Me.ActInstIdField
            End Get
            Set
                If (Me.ActInstIdField.Equals(value) <> true) Then
                    Me.ActInstIdField = value
                    Me.RaisePropertyChanged("ActInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActivityDestinationInstance() As WorkflowServer.ActivityDestinationInstance
            Get
                Return Me.ActivityDestinationInstanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActivityDestinationInstanceField, value) <> true) Then
                    Me.ActivityDestinationInstanceField = value
                    Me.RaisePropertyChanged("ActivityDestinationInstance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActivityInstance() As WorkflowServer.ActivityInstance
            Get
                Return Me.ActivityInstanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActivityInstanceField, value) <> true) Then
                    Me.ActivityInstanceField = value
                    Me.RaisePropertyChanged("ActivityInstance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActivityName() As String
            Get
                Return Me.ActivityNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActivityNameField, value) <> true) Then
                    Me.ActivityNameField = value
                    Me.RaisePropertyChanged("ActivityName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set
                If (Me.CreateDateField.Equals(value) <> true) Then
                    Me.CreateDateField = value
                    Me.RaisePropertyChanged("CreateDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Destination() As String
            Get
                Return Me.DestinationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationField, value) <> true) Then
                    Me.DestinationField = value
                    Me.RaisePropertyChanged("Destination")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DestinationSlot() As WorkflowServer.DestinationSlot
            Get
                Return Me.DestinationSlotField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationSlotField, value) <> true) Then
                    Me.DestinationSlotField = value
                    Me.RaisePropertyChanged("DestinationSlot")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventInstId() As Integer
            Get
                Return Me.EventInstIdField
            End Get
            Set
                If (Me.EventInstIdField.Equals(value) <> true) Then
                    Me.EventInstIdField = value
                    Me.RaisePropertyChanged("EventInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemData() As String
            Get
                Return Me.ItemDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemDataField, value) <> true) Then
                    Me.ItemDataField = value
                    Me.RaisePropertyChanged("ItemData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Originator() As String
            Get
                Return Me.OriginatorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginatorField, value) <> true) Then
                    Me.OriginatorField = value
                    Me.RaisePropertyChanged("Originator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Priority() As WorkflowServer.ProcessInstance.ProcessPriority
            Get
                Return Me.PriorityField
            End Get
            Set
                If (Me.PriorityField.Equals(value) <> true) Then
                    Me.PriorityField = value
                    Me.RaisePropertyChanged("Priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcInstId() As Integer
            Get
                Return Me.ProcInstIdField
            End Get
            Set
                If (Me.ProcInstIdField.Equals(value) <> true) Then
                    Me.ProcInstIdField = value
                    Me.RaisePropertyChanged("ProcInstId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcSchemeDisplayName() As String
            Get
                Return Me.ProcSchemeDisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcSchemeDisplayNameField, value) <> true) Then
                    Me.ProcSchemeDisplayNameField = value
                    Me.RaisePropertyChanged("ProcSchemeDisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessDisplayName() As String
            Get
                Return Me.ProcessDisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessDisplayNameField, value) <> true) Then
                    Me.ProcessDisplayNameField = value
                    Me.RaisePropertyChanged("ProcessDisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessInstance() As WorkflowServer.ProcessInstance
            Get
                Return Me.ProcessInstanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessInstanceField, value) <> true) Then
                    Me.ProcessInstanceField = value
                    Me.RaisePropertyChanged("ProcessInstance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessName() As String
            Get
                Return Me.ProcessNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessNameField, value) <> true) Then
                    Me.ProcessNameField = value
                    Me.RaisePropertyChanged("ProcessName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As WorkflowServer.WorklistItemStatu
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActivityDestinationInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ActivityDestinationInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivityNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataFieldsField() As WorkflowServer.DataFieldDefinitionWithValue
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationUserField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As WorkflowServer.ActivityStatus
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActivityName() As String
            Get
                Return Me.ActivityNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActivityNameField, value) <> true) Then
                    Me.ActivityNameField = value
                    Me.RaisePropertyChanged("ActivityName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataFields() As WorkflowServer.DataFieldDefinitionWithValue()
            Get
                Return Me.DataFieldsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataFieldsField, value) <> true) Then
                    Me.DataFieldsField = value
                    Me.RaisePropertyChanged("DataFields")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DestinationUser() As String
            Get
                Return Me.DestinationUserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationUserField, value) <> true) Then
                    Me.DestinationUserField = value
                    Me.RaisePropertyChanged("DestinationUser")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartTime() As Date
            Get
                Return Me.StartTimeField
            End Get
            Set
                If (Me.StartTimeField.Equals(value) <> true) Then
                    Me.StartTimeField = value
                    Me.RaisePropertyChanged("StartTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As WorkflowServer.ActivityStatus
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActivityStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model")>  _
    Public Enum ActivityStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Running = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Active = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Completed = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Expired = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActivityInstance", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ActivityInstance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivityNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As WorkflowServer.ActivityStatus
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActivityName() As String
            Get
                Return Me.ActivityNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActivityNameField, value) <> true) Then
                    Me.ActivityNameField = value
                    Me.RaisePropertyChanged("ActivityName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartDate() As Date
            Get
                Return Me.StartDateField
            End Get
            Set
                If (Me.StartDateField.Equals(value) <> true) Then
                    Me.StartDateField = value
                    Me.RaisePropertyChanged("StartDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As WorkflowServer.ActivityStatus
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DestinationSlot", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DestinationSlot
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinationUsersField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SlotIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DestinationUsers() As String()
            Get
                Return Me.DestinationUsersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinationUsersField, value) <> true) Then
                    Me.DestinationUsersField = value
                    Me.RaisePropertyChanged("DestinationUsers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SlotId() As Integer
            Get
                Return Me.SlotIdField
            End Get
            Set
                If (Me.SlotIdField.Equals(value) <> true) Then
                    Me.SlotIdField = value
                    Me.RaisePropertyChanged("SlotId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WorklistItemStatu", [Namespace]:="http://schemas.datacontract.org/2004/07/MyIdealProp.Workflow.Core.Model")>  _
    Public Enum WorklistItemStatu As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Avaiable = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Open = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Allocated = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Completed = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Expired = 4
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WorkflowServer.IWorkflowService")>  _
    Public Interface IWorkflowService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/CreateProcessInstance", ReplyAction:="http://tempuri.org/IWorkflowService/CreateProcessInstanceResponse")>  _
        Function CreateProcessInstance(ByVal procName As String) As WorkflowServer.ProcessInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/StartProcessInstance", ReplyAction:="http://tempuri.org/IWorkflowService/StartProcessInstanceResponse")>  _
        Function StartProcessInstance(ByVal procName As String, ByVal DisplayName As String, ByVal priority As WorkflowServer.ProcessInstance.ProcessPriority, ByVal dataFields As System.Collections.Generic.Dictionary(Of String, Object)) As WorkflowServer.ProcessInstance
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/ExpiredProcessInstance", ReplyAction:="http://tempuri.org/IWorkflowService/ExpiredProcessInstanceResponse")>  _
        Sub ExpiredProcessInstance(ByVal procInstId As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetProcessInstancesByDataFields", ReplyAction:="http://tempuri.org/IWorkflowService/GetProcessInstancesByDataFieldsResponse")>  _
        Function GetProcessInstancesByDataFields(ByVal procName As String, ByVal key As String, ByVal value As String) As Integer()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetWorkList", ReplyAction:="http://tempuri.org/IWorkflowService/GetWorkListResponse")>  _
        Function GetWorkList() As WorkflowServer.WorklistItem()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/CompleteWorkList", ReplyAction:="http://tempuri.org/IWorkflowService/CompleteWorkListResponse")>  _
        Sub CompleteWorkList(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal datafields As System.Collections.Generic.Dictionary(Of String, Object))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/CompleteDestInstWorklist", ReplyAction:="http://tempuri.org/IWorkflowService/CompleteDestInstWorklistResponse")>  _
        Sub CompleteDestInstWorklist(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal datafields As System.Collections.Generic.Dictionary(Of String, Object), ByVal actDataFields As System.Collections.Generic.Dictionary(Of String, Object))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/OpenWorkListItem", ReplyAction:="http://tempuri.org/IWorkflowService/OpenWorkListItemResponse")>  _
        Function OpenWorkListItem(ByVal procInstId As Integer, ByVal actInstId As Integer) As WorkflowServer.WorklistItem
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/UpdateWorklistItem", ReplyAction:="http://tempuri.org/IWorkflowService/UpdateWorklistItemResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.ProcessInstance)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinitionWithValue())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinitionWithValue)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.DataFieldDefinition)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.BaseDefinition)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.ProcessInstance.ProcessPriority)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.WorklistItem())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.WorklistItem)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.ActivityDestinationInstance)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.ActivityStatus)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.ActivityInstance)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.DestinationSlot)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(WorkflowServer.WorklistItemStatu)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Integer())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function UpdateWorklistItem(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal dataFields As System.Collections.Generic.Dictionary(Of String, Object)) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GotoActivity", ReplyAction:="http://tempuri.org/IWorkflowService/GotoActivityResponse")>  _
        Sub GotoActivity(ByVal procInstId As Integer, ByVal actName As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWorkflowServiceChannel
        Inherits WorkflowServer.IWorkflowService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WorkflowServiceClient
        Inherits System.ServiceModel.ClientBase(Of WorkflowServer.IWorkflowService)
        Implements WorkflowServer.IWorkflowService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreateProcessInstance(ByVal procName As String) As WorkflowServer.ProcessInstance Implements WorkflowServer.IWorkflowService.CreateProcessInstance
            Return MyBase.Channel.CreateProcessInstance(procName)
        End Function
        
        Public Function StartProcessInstance(ByVal procName As String, ByVal DisplayName As String, ByVal priority As WorkflowServer.ProcessInstance.ProcessPriority, ByVal dataFields As System.Collections.Generic.Dictionary(Of String, Object)) As WorkflowServer.ProcessInstance Implements WorkflowServer.IWorkflowService.StartProcessInstance
            Return MyBase.Channel.StartProcessInstance(procName, DisplayName, priority, dataFields)
        End Function
        
        Public Sub ExpiredProcessInstance(ByVal procInstId As Integer) Implements WorkflowServer.IWorkflowService.ExpiredProcessInstance
            MyBase.Channel.ExpiredProcessInstance(procInstId)
        End Sub
        
        Public Function GetProcessInstancesByDataFields(ByVal procName As String, ByVal key As String, ByVal value As String) As Integer() Implements WorkflowServer.IWorkflowService.GetProcessInstancesByDataFields
            Return MyBase.Channel.GetProcessInstancesByDataFields(procName, key, value)
        End Function
        
        Public Function GetWorkList() As WorkflowServer.WorklistItem() Implements WorkflowServer.IWorkflowService.GetWorkList
            Return MyBase.Channel.GetWorkList
        End Function
        
        Public Sub CompleteWorkList(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal datafields As System.Collections.Generic.Dictionary(Of String, Object)) Implements WorkflowServer.IWorkflowService.CompleteWorkList
            MyBase.Channel.CompleteWorkList(procInstId, actInstId, datafields)
        End Sub
        
        Public Sub CompleteDestInstWorklist(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal datafields As System.Collections.Generic.Dictionary(Of String, Object), ByVal actDataFields As System.Collections.Generic.Dictionary(Of String, Object)) Implements WorkflowServer.IWorkflowService.CompleteDestInstWorklist
            MyBase.Channel.CompleteDestInstWorklist(procInstId, actInstId, datafields, actDataFields)
        End Sub
        
        Public Function OpenWorkListItem(ByVal procInstId As Integer, ByVal actInstId As Integer) As WorkflowServer.WorklistItem Implements WorkflowServer.IWorkflowService.OpenWorkListItem
            Return MyBase.Channel.OpenWorkListItem(procInstId, actInstId)
        End Function
        
        Public Function UpdateWorklistItem(ByVal procInstId As Integer, ByVal actInstId As Integer, ByVal dataFields As System.Collections.Generic.Dictionary(Of String, Object)) As Object Implements WorkflowServer.IWorkflowService.UpdateWorklistItem
            Return MyBase.Channel.UpdateWorklistItem(procInstId, actInstId, dataFields)
        End Function
        
        Public Sub GotoActivity(ByVal procInstId As Integer, ByVal actName As String) Implements WorkflowServer.IWorkflowService.GotoActivity
            MyBase.Channel.GotoActivity(procInstId, actName)
        End Sub
    End Class
End Namespace
