'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EscalationInstance
    Public Property EscalationId As Integer
    Public Property ProcInstId As Integer
    Public Property ActInstId As Integer
    Public Property DueTime As Date
    Public Property ActionName As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property ExecuteTime As Nullable(Of Date)
    Public Property Status As String
    Public Property RepeatNo As Nullable(Of Integer)

End Class
