'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventInstance
    Public Property Id As Integer
    Public Property ActInstId As Integer
    Public Property Name As String
    Public Property Type As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property ProcInstId As Integer
    Public Property Status As Nullable(Of Integer)

End Class
