'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LineInstance
    Public Property Id As Integer
    Public Property ProcInstId As Integer
    Public Property From As String
    Public Property [To] As String
    Public Property RuleResult As Nullable(Of Boolean)
    Public Property CreateDate As Nullable(Of Date)

End Class
