'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessInstance
    Public Property Id As Integer
    Public Property ProcessId As Integer
    Public Property DisplayName As String
    Public Property Originator As String
    Public Property Description As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property Priority As Nullable(Of Integer)
    Public Property Archived As Nullable(Of Boolean)

End Class
