'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessScheme
    Public Property ProcessId As Integer
    Public Property Name As String
    Public Property Version As Nullable(Of Integer)
    Public Property IsDefault As Nullable(Of Boolean)
    Public Property Scheme As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property DisplayName As String
    Public Property Description As String

End Class
