'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PortalLeadsView
    Public Property BBLE As String
    Public Property PropertyAddress As String
    Public Property InPortal As Integer
    Public Property LeadsName As String
    Public Property EmployeeID As Nullable(Of Integer)
    Public Property EmployeeName As String
    Public Property UserActive As Nullable(Of Boolean)
    Public Property Team As String
    Public Property Status As Nullable(Of Integer)
    Public Property StatusName As String
    Public Property AssignDate As Nullable(Of Date)
    Public Property LastUpdate As Nullable(Of Date)

End Class
