'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CommonService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CommonService.ICommonService")>  _
    Public Interface ICommonService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICommonService/SendMessage", ReplyAction:="http://tempuri.org/ICommonService/SendMessageResponse")>  _
        Sub SendMessage(ByVal userName As String, ByVal title As String, ByVal msg As String, ByVal bble As String, ByVal notifyTime As Date, ByVal createBy As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICommonService/SendEmailByTemplate", ReplyAction:="http://tempuri.org/ICommonService/SendEmailByTemplateResponse")>  _
        Sub SendEmailByTemplate(ByVal userName As String, ByVal templateName As String, ByVal emailData As System.Collections.Generic.Dictionary(Of String, String))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICommonService/SendEmail", ReplyAction:="http://tempuri.org/ICommonService/SendEmailResponse")>  _
        Sub SendEmail(ByVal userName As String, ByVal subject As String, ByVal body As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICommonService/UpdateLeadsSearchStatus", ReplyAction:="http://tempuri.org/ICommonService/UpdateLeadsSearchStatusResponse")>  _
        Sub UpdateLeadsSearchStatus(ByVal leadsSearchId As Integer, ByVal status As Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICommonServiceChannel
        Inherits CommonService.ICommonService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CommonServiceClient
        Inherits System.ServiceModel.ClientBase(Of CommonService.ICommonService)
        Implements CommonService.ICommonService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub SendMessage(ByVal userName As String, ByVal title As String, ByVal msg As String, ByVal bble As String, ByVal notifyTime As Date, ByVal createBy As String) Implements CommonService.ICommonService.SendMessage
            MyBase.Channel.SendMessage(userName, title, msg, bble, notifyTime, createBy)
        End Sub
        
        Public Sub SendEmailByTemplate(ByVal userName As String, ByVal templateName As String, ByVal emailData As System.Collections.Generic.Dictionary(Of String, String)) Implements CommonService.ICommonService.SendEmailByTemplate
            MyBase.Channel.SendEmailByTemplate(userName, templateName, emailData)
        End Sub
        
        Public Sub SendEmail(ByVal userName As String, ByVal subject As String, ByVal body As String) Implements CommonService.ICommonService.SendEmail
            MyBase.Channel.SendEmail(userName, subject, body)
        End Sub
        
        Public Sub UpdateLeadsSearchStatus(ByVal leadsSearchId As Integer, ByVal status As Integer) Implements CommonService.ICommonService.UpdateLeadsSearchStatus
            MyBase.Channel.UpdateLeadsSearchStatus(leadsSearchId, status)
        End Sub
    End Class
End Namespace
